### ISSUE TITLE
Error after upgrade HA to 2025.1.0

### ISSUE THREAD

**Issue by Marcin685** [dadge/awesome_thermostat#20]
Add your logs here.

Platform error 'climate' from integration 'awesome_thermostat' - cannot import name 'CURRENT_HVAC_COOL' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)

**Comment by jimbovp** [comment]
Same issue here. Any workarounds?
Did a rollback to 2024.12.5 and its working again. But would be nice to be able to upgrade at some point... :-)

**Comment by tigers75** [comment]
it'd be nice to know if @dadge is still developing the add-on so that maybe someone can step-up.
With a breaking change like this it's going to become obsolete soon (we can't hold back updating forever), so I'll have to find an alternative. Unfortunately I can't program in python well enough to be of some help.

**Comment by Marcin685** [comment]
alternative software that I switched to and it works very well with the new version of HA

https://github.com/jmcollin78/versatile_thermostat

**Comment by dorupetruc** [comment]
Check my commit & pull request . With these changes the awesome_thermostat  started working again on my HA instance and my home is warm &  cozy again :)

**Comment by michaeldufour** [comment]
> Check my commit & pull request . With these changes the awesome_thermostat started working again on my HA instance and my home is warm & cozy again :)

Thanks @dorupetruc work fine  now!

**Comment by jakass202** [comment]
@dorupetruc how do we add your PR to hacs ?

**Comment by cata747** [comment]
edit again: home assistant -> developer tools -> upper bar ACTIONS then choose action Update: Install update
choose device awesome_thermostat then check version and insert "e77bb569a777bd2a0664d07996c2dcce296c4aba" without quotes

**Comment by byxil** [comment]
not work for me.
I replaced the single file, but also the entire awesome_thermostat folder, but nothing.
The update proposed by @cata747 does not give an error, but it does not work like that either.
When I update to 2025.1.1 the thermostat no longer works

**Comment by jimbovp** [comment]
> edit again: home assistant -> developer tools -> upper bar ACTIONS then choose action Update: Install update choose device awesome_thermostat then check version and insert "e77bb569a777bd2a0664d07996c2dcce296c4aba" without quotes

Nice work, just to check, will that work for "simple_thermostat" as well?
If I'm not mistaken, this is the previous, unmaintained version of awesome_thermostat which I'm still using. If not, I will probably need to switch to awesome...

**Comment by michaeldufour** [comment]
> > edit again: home assistant -> developer tools -> upper bar ACTIONS then choose action Update: Install update choose device awesome_thermostat then check version and insert "e77bb569a777bd2a0664d07996c2dcce296c4aba" without quotes
> 
> Nice work, just to check, will that work for "simple_thermostat" as well? If I'm not mistaken, this is the previous, unmaintained version of awesome_thermostat which I'm still using. If not, I will probably need to switch to awesome...

Yes it's the first version you can migrate with Awesome Thermostat with the las modification of @dorupetruc

**Comment by byxil** [comment]
I don't understand how I can apply this fix, I don't see a file to download and what I tried to do doesn't work.
Can someone help me and tell a stupid person how to do it?

**Comment by cata747** [comment]
Honestly I'm not an expert myself, I use HA on a virtual machine and for me
the "fix" is working as it should. After the fix HACS asks to update the
repository and you shouldn't because you will only broke it again. The
steps you need to take will use the developer options in home assistant.
Maybe you don't see that in your version of HA. I don't know which steps
you have problems with.

**Comment by byxil** [comment]
> Honestly I'm not an expert myself, I use HA on a virtual machine and for me the "fix" is working as it should. After the fix HACS asks to update the repository and you shouldn't because you will only broke it again. The steps you need to take will use the developer options in home assistant. Maybe you don't see that in your version of HA. I don't know which steps you have problems with.
> […](#)

thanks for the reply, as I wrote in my first message, I tried to replace the climate.py file by taking it from dorupetruc's gith, but it didn't work.
I tried to select the service, but even putting the string suggested by cata747, nothing happens.
When I update the HA version, the thermostat doesn't work anymore
I have a thermostat on a switch with which I use a temperature sensor and with the 2024.12.5 version everything works fine.

**Comment by cata747** [comment]
The commit with that code do exactly that. Replace all files original files
with files modified by @dorupetruc. The steps of the fix you must apply on
web interface of home assistant on left menu developer tools. I would
redownload the broken one and apply the commit using the steps indicated to
ensure you start clean. Those are the steps I apply myself and it's
working. I am sorry if I can't help you more

**Comment by foddy-foo** [comment]
I also had problems with awesome_thermostat after upgrading from HA 2024.12.5 to 2025.2.1 
error seen:
**This entity is no longer being provided by the awesome_thermostat integration. If the entity is no longer in use, delete it in settings**

Tried the suggestion from cata747 regarding the developer tools and "e77bb569a777bd2a0664d07996c2dcce296c4aba", then did a reboot but the problem persisted. I then did a redownload to clear that out and then tried replacing the files from dorupetruc, overwriting the original ones. Did another reboot but still had the problems. I have had to roll back my VM to the snapshot I took before the 2025.2.1 upgrade.

**Comment by byxil** [comment]
> Tried the suggestion from cata747 regarding the developer tools and "e77bb569a777bd2a0664d07996c2dcce296c4aba", then did a reboot but the problem persisted. I then did a redownload to clear that out and then tried replacing the files from dorupetruc, overwriting the original ones. Did another reboot but still had the problems. I have had to roll back my VM to the snapshot I took before the 2025.2.1 upgrade.


try to restart the host, I solved it like this.

**Comment by foddy-foo** [comment]
> > Tried the suggestion from cata747 regarding the developer tools and "e77bb569a777bd2a0664d07996c2dcce296c4aba", then did a reboot but the problem persisted. I then did a redownload to clear that out and then tried replacing the files from dorupetruc, overwriting the original ones. Did another reboot but still had the problems. I have had to roll back my VM to the snapshot I took before the 2025.2.1 upgrade.
> 
> try to restart the host, I solved it like this.

Thanks for your suggestion byxil. Unfortunately I have already tried rebooting the Home Assistant VM and also shutting it down after copying the new files from dorupetruc. Neither things helped. I note that you are saying I should try restarting the host but I'm running lot's of other VM's on my Proxmox hypervisor so it's not straightforward for me to restart the entire environment and I'm not sure that this is going to do anything more than a shutdown of the Home Assistant VM really.  In the end I edited my configuration.yaml and replaced this:
``` 
climate:
  - platform: awesome_thermostat
    name: Home heating
```
with this:

```
climate:
  - platform: generic_thermostat
    name: Home heating
```

I thought it might mean I'd loose the presents but I don't seem to have lost anything really by using the built in generic thermostat compared to the awesome thermostat. I'm assuming the generic thermostat ended up getting the extra features at some point making the awesome thermostat a bit redundant. So now I'm not dependant on the awesome thermostat I'm going to attempt the HA Core update to 2025.2.1

EDIT: After moving to the generic_thermostat my upgrade of HA core to 2025.2.1 went well, no issues seen.

**Comment by omnitetranet** [comment]
Same error either with simple_thermostat and awesome_thermostat:

Platform error 'climate' from integration 'awesome_thermostat' - cannot import name 'CURRENT_HVAC_COOL' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)

Generic_thermostat works, but have limited characteristics and versatile_thermostat is unable to switch on and off correctly the switch that work in a sort of "very low frequency PWM" that causes a continuous temperature dropping...for my installation is totally unusable and the author don't want to implement the simple logic of the general_thermostat into his addon.

The rollback to a 2024 backup don't work anymore and now I haven't a working thermostat anymore.

**Comment by AJolly** [comment]
Yeah I tried using versatile thermostat but was unable to get into work
like awesome thermostat. Really I just need a generic thermostat with
higher precision.

**Comment by OttoUsualConsumer** [comment]
Hi there, same bug for me.
fresh install of all files, did the update like above with 'e77bb569a777bd2a0664d07996c2dcce296c4aba', restarted and same error message.

**Comment by nonameplum** [comment]
I also couldn't update with developer tools by:
> home assistant -> developer tools -> upper bar ACTIONS then choose action Update: Install update
choose device awesome_thermostat then check version and insert "e77bb569a777bd2a0664d07996c2dcce296c4aba" without quotes

But you can just copy the content of the file changed in this commit https://github.com/dadge/awesome_thermostat/blob/e77bb569a777bd2a0664d07996c2dcce296c4aba/custom_components/awesome_thermostat/climate.py and replace it in your Home Assistant manually, e.g. by using Studio Code Server in 
`/config/custom_components/awesome_thermostat/climate.py`

It worked for me.
